# Site settings
# accessible in the templates via {{ site.myvariable }}.
title: Binary Sun - Online Games
description: >
  Binary Sun is an online games site focusing on games that work on every platform; from desktop computer, to tablet, and phone.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: binarymoon
permalink: /blog/:year/:title/

# Collections
collections:
  games:
    output: true

# Default properties
defaults:
  - scope:
      type: games
    values:
      layout: game

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
include:
  - _pages
