# Site settings
# accessible in the templates via {{ site.myvariable }}.
title: Binary Sun - Online Games
description: >
  Binary Sun is an online games site focusing on games that work on every platform. We publish HTML5 browser based games for desktop computer, tablet, and phone.
baseurl: ""
url: ""
twitter_username: binarymoon
permalink: /blog/:year/:title/

# Collections
collections:
  games:
    output: true

# Default properties
defaults:
  - scope:
      type: games
    values:
      layout: game

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
include:
  - _pages
