# Site settings
# accessible in the templates via {{ site.myvariable }}.
title: Binary Sun
description: >
  Binary Sun is an online games site focusing on games that work on every platform. We publish HTML5 browser based games for desktop computer, tablet, and phone.
baseurl: ""
url: ""
twitter_username: binarymoon
permalink: /blog/:year/:title/
google_analytics: UA-55722-3

# SEO
twitter:
  username: binarymoon
webmaster_verifications:
  google: jpX5pDZ1_vsfHTm74TkvqTO5U5hjbpzsj6gnjuVeQXs

# Collections
collections:
  games:
    output: true
  free-games:
    output: true

# Default properties
defaults:
  - scope:
      type: games
    values:
      layout: game

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
include:
  - _pages
